### ISSUE TITLE
Cannot work under vue setup script 

### ISSUE THREAD

**Issue by iceprosurface** [kisstkondoros/codemetrics#102]
<img width="219" alt="image" src="https://user-images.githubusercontent.com/16058059/188264435-3c8974ba-41ac-42bc-8db8-96882bf209fa.png">

<img width="265" alt="image" src="https://user-images.githubusercontent.com/16058059/188264444-21368736-d815-4006-baba-42c31cdb045c.png">

**Comment by iceprosurface** [comment]
https://github.com/kisstkondoros/codemetrics/blob/master/src/metrics/server/MetricsParserUtil.ts#L31

Change `/<script lang="js">/gim` -> `<script(\s*setup)? lang="js"(\s*setup)?>`?

**Comment by iceprosurface** [comment]
```
<script( +setup)?( lang="(js|ts)")?( +setup)?>
```
<img width="581" alt="image" src="https://user-images.githubusercontent.com/16058059/188264788-4d29d214-dae9-4123-a50d-40ee1eccadb3.png">

**Comment by kisstkondoros** [comment]
published with 1.25.2
