### ISSUE TITLE
Option to ignore "Describe" functions

### ISSUE THREAD

**Issue by lianestellet** [kisstkondoros/codemetrics#104]
I use jest on my team and usually our describes have a lot of complexity due to it's structure.
Should we have a configuration to ignore exactly some function function name?

something like this:
codemetrics.basics.CodeIgnoreFunctionNames: ["describe"]

**Comment by kisstkondoros** [comment]
Implemented in tsmetrics-core@1.4.0, available in vscode-codemetrics@1.26.0.

Can be configured as
```json
{
    "codemetrics.basics.IgnoredFunctionNames": [
        "describe"
    ]
}
```
