### ISSUE TITLE
Any plans to extend this for Java?

### ISSUE THREAD

**Issue by amith-kumarg** [kisstkondoros/codemetrics#112]

**Comment by kisstkondoros** [comment]
There is https://github.com/kisstkondoros/codemetrics-idea for intellij idea. I have no plans extending this extension for further languages (at least not in the short term)

**Comment by amith-kumarg** [comment]
Yes I am aware of the one for Intellij, already using it and its tremendously helpful, really appreciate all you do. I am evaluating options to switch to VSCode, just one IDE, for all my languages development, so was wondering if this VSCode extension itself can be extended to include Java?
