### ISSUE TITLE
Change color

### ISSUE THREAD

**Issue by albohlabs** [kisstkondoros/codemetrics#12]
How can i change the color of the typo?

<img width="194" alt="bildschirmfoto 2017-02-17 um 13 55 04" src="https://cloud.githubusercontent.com/assets/163665/23066023/b91e196e-f518-11e6-9a2e-fd2909dcf9d8.png">

**Comment by kisstkondoros** [comment]
Can not be controlled from the extension nor from the user settings 😒 

As far as I can tell it is hard coded in the vscode sources:
https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/codelens/browser/codelens.css

Similar issue reported in the vscode repo:
https://github.com/Microsoft/vscode/issues/16038

**Comment by albohlabs** [comment]
Thank you for the info.
