### ISSUE TITLE
switch case statement heavy ?

### ISSUE THREAD

**Issue by ronkats** [kisstkondoros/codemetrics#14]
Why is this counted for 12 points?
`function textChoiceToNumber(value) {

    switch (value) {
        case 1:
            return 'one';
        case 2:
            return 'two';
        case 3:
            return 'three';
        case 4:
            return 'four';
        default:
            return value;
    }
}`

**Comment by kisstkondoros** [comment]
If you click on the codelens it will provide you a quickpick menu where you can see the explanation in detail.
smth. like this
![image](https://cloud.githubusercontent.com/assets/14231157/23943692/9646b8e4-0970-11e7-8cd1-ed776bc7237b.png)


As you can see it comes out from the followings:
- **return statements** -> +1 for each = **+5**
- **case clauses** -> +1 for each = **+5**
  - this includes the default case clause as well
-  **switch statement** -> **+1**
- the **function declaration** which contains all of this (this is not shown in the quickpick) -> **+1**

IMO this is correct (even if it might not be correct according to [Cyclomatic_complexity](https://en.wikipedia.org/wiki/Cyclomatic_complexity)).

You can adjust the settings to exclude e.g. the return statements and / or the case clauses from the calculation:
```json
"codemetrics.nodeconfiguration.ReturnStatement": 0,
"codemetrics.nodeconfiguration.CaseClause": 0,
"codemetrics.nodeconfiguration.DefaultClause": 0
```

But please consider the following refactoring instead:
![image](https://cloud.githubusercontent.com/assets/14231157/23943988/8bfc556e-0971-11e7-8007-e67ac36feae8.png)

**Comment by ronkats** [comment]
Sorry for the late respons, but thanks for your explanation and refactored version.
