### ISSUE TITLE
Some arrow functions are not displaying codelens

### ISSUE THREAD

**Issue by mikiest** [kisstkondoros/codemetrics#15]
Arrow functions similarly written will not always display a codelense, despite having `Toggle codelense for arrow functions` enabled and the following setting:

`"codemetrics.basics.CodeLensHiddenUnder": 0`

See screenshot below:

![image](https://cloud.githubusercontent.com/assets/15056200/24140078/a3a6ad50-0e16-11e7-8092-8b2b5e560b1c.png)

VS Code: 1.10.2
CodeMetrics: 1.2.0
TypeScript: 2.2.1

**Comment by kisstkondoros** [comment]
Could you please provide a small code sample? I can't reproduce it unfortunately.

**Comment by mikiest** [comment]
I've done a few tests, and it appears that a method with **0 complexity will not display any codelense**, see below:

![image](https://cloud.githubusercontent.com/assets/15056200/24206921/96529374-0f17-11e7-9c5a-c869d4928d99.png)

I've heavily customised my complexity score settings so `doThing` method's complexity is 0.

Is this expected? `CodeLensHiddenUnder` seems to mean that anything **under** 0 will not be displayed, so 0 **should** definitely be displayed (which is what I'd like) imo.

**Comment by kisstkondoros** [comment]
Version 1.2.2 should contain the fix. Thanks for spotting it.

However I strongly recommend to have a realistic configuration, this way you might trick yourself 😉
