### ISSUE TITLE
"IfWithElseStatement" setting type incorrect

### ISSUE THREAD

**Issue by mikiest** [kisstkondoros/codemetrics#16]
the `codemetrics.nodeconfiguration.IfWithElseStatement` setting expected type is `string`, although all other complexity settings are `numbers`.

See below:
![image](https://cloud.githubusercontent.com/assets/15056200/24141135/64191aa2-0e1a-11e7-938d-e7d1961f9cb5.png)
![image](https://cloud.githubusercontent.com/assets/15056200/24141195/9e9b44a2-0e1a-11e7-8bdf-5f175c868ba0.png)

VS Code: 1.10.2
CodeMetrics: 1.2.0

**Comment by kisstkondoros** [comment]
Thanks for the issue report!
It should be fixed in version 1.2.1 which should already be available in the market!
