### ISSUE TITLE
Is there a way to hide class complexity?

### ISSUE THREAD

**Issue by Aedaeum** [kisstkondoros/codemetrics#18]
I noticed that class complexity is the sum of its parts, but I think if you're going to do that, then there needs to be some sort of acceptable baseline that isn't dependent on the calculation of the function complexity.

A class is made up of _methods_, _properties_, and potentially a _constructor_. The complexity of the methods themselves should play an insignificant role in the complexity of the overall Class; possibly 5% of the method complexity, rounded up towards the Class complexity threshold.

**The baselines that need to be established are as follows**
* What is the complexity of the constructor?
* What is an appropriate number of methods for a Class?
* What is an appropriate number of properties for a Class?
  * Are the properties being set with a ternary condition?
    * What is the complexity of the operation?
  * Is a property being set with a closure?
    * What is the complexity of the operation?
  * Are there getters/setters?
    * What is the complexity of the operation?
* When reading the code of a Class, what exactly causes the most difficulty?

I believe no matter what, this is a very subjective complexity assessment, seeing as Classes are inherently contextual. Because of this, in the interim, it would be nice to be able to hide the current vastly inaccurate assessment of Classes.

Thanks for your time ❤️

**Comment by kisstkondoros** [comment]
Hi,

I understand your opinion, even if I don't agree with it 😄 
I think what is actually wrong is the textual representation for a given complexity.

Until we can come up with something better one can use a (yet) undocumented setting:
"codemetrics.nodeconfiguration.MetricsForClassDeclarationsToggled": false

**Comment by kisstkondoros** [comment]
I saw you've opened a fork, further changes in this area are more than welcome 😉

**Comment by Aedaeum** [comment]
Thanks 😄 

**BTW** I don't know what you looked at, but I have not created a fork.
