### ISSUE TITLE
Feature request: complexity hinting on the sidelines

### ISSUE THREAD

**Issue by emilio-martinez** [kisstkondoros/codemetrics#19]
I this package brings something really interesting to the table; however, I simply cannot bring myself to use it with having the tiny type next to my code. Is it possible to show codemetrics' messaging via icons next to the numbers? This is a common pattern used by linters, for example.

**Comment by kisstkondoros** [comment]
Hi, check out version 1.5.0 it comes with inline text decorations turned on by default.
You can control the appearance by the following settings:
  - "codemetrics.basics.DecorationModeEnabled"
    - hides inline decorations if set to false
  - "codemetrics.basics.CodeLensEnabled"
    - hides code lenses if set to false
