### ISSUE TITLE
add config option to ignore files matching a glob/pattern

### ISSUE THREAD

**Issue by mutsys** [kisstkondoros/codemetrics#20]
It would be awesome if there was an option to tell CodeMetrics to ignore files whose path matches a glob/pattern, specifically `node_modules/**/*`. Often times when I drill down to the TypeScript definition or source for an `npm` package, VSCode will freeze for while as CodeMetrics does its work. In general, I don't really care about the metrics or complexity of a dependency. I would like to be able to tell CodeMetrics to ignore those files altogether. In the meanwhile, I am trying out `codemetrics.basics.FileSizeLimitMB` to see if it can be adjusted to a reasonable value that will filter out large files from dependencies without impacting my ability to analyze my own source files.

**Comment by kisstkondoros** [comment]
Hi there!

Actually that was the intention behind `codemetrics.basics.FileSizeLimitMB`, let me know if you could fine tune it for your purpose.
To be honest I don't want to introduce a glob pattern mechanism for this.
Actually the solution would be to move it off the UI thread, but I was too lazy to implement it 😄

**Comment by kisstkondoros** [comment]
Check out 1.6.0 🔥 I've just moved the heavy computation stuff off the UI thread. 
Should be non blocking for any file size / complexity.
I've tried it with typescript's tsc.js, while setting the files size limit to 2 MB (for the version in the demo project it was just enough), it was a pain for the CPU indeed, but it did not caused any lag in vscode. 😄

**Comment by kisstkondoros** [comment]
Feel free to open a new issue if it still feels odd.

**Comment by mutsys** [comment]
I've done a bit of experimentation and it seems that setting `codemetrics.basics.FileSizeLimitMB` to 0.05 works pretty well. Now I have a different problem, not related at all to **CodeMetrics**. Now **TypeLens** seems to be the source of pain. And what do you know, that's you're baby too. I will check out the issues there and create a new one if necessary.
