### ISSUE TITLE
Metrics

### ISSUE THREAD

**Issue by cbfranca** [kisstkondoros/codemetrics#22]
What were the metrics used as a reference?

**Comment by kisstkondoros** [comment]
Maybe I misunderstood the question, but:
The "shipped" configuration is intended to compute a similar metric as [McCabe](https://en.wikipedia.org/wiki/Cyclomatic_complexity) complexity, but it is not entirely the same.

To be honest I've written the same analyzer for Java before and took the idea from it. There it worked pretty well, and I thought why not do the same for TypeScript (and of course for JavaScript). The TSX and JSX support came after that.

While I know it is not perfect, it is good enough to indicate that something has to be done - maybe just a comment about why it couldn't / shouldn't be changed etc.

I expected feedback from the community to do adjustments, but there were nothing besides #18 and #21.

Any feedback is appreciated 😄

**Comment by gujunhk** [comment]
> Maybe I misunderstood the question, but:
> The "shipped" configuration is intended to compute a similar metric as [McCabe](https://en.wikipedia.org/wiki/Cyclomatic_complexity) complexity, but it is not entirely the same.
> 
> To be honest I've written the same analyzer for Java before and took the idea from it. There it worked pretty well, and I thought why not do the same for TypeScript (and of course for JavaScript). The TSX and JSX support came after that.
> 
> While I know it is not perfect, it is good enough to indicate that something has to be done - maybe just a comment about why it couldn't / shouldn't be changed etc.
> 
> I expected feedback from the community to do adjustments, but there were nothing besides #18 and #21.
> 
> Any feedback is appreciated 😄

CodeMetrics is amazing. I'm interested in your complexity analyzer for Java. Is it uploaded to the Jetbrains Marketplace?

**Comment by kisstkondoros** [comment]
No but I'll try to dig that out from somewhere and put it online if possible

**Comment by kisstkondoros** [comment]
:drum: 
https://github.com/kisstkondoros/codemetrics-idea
https://plugins.jetbrains.com/plugin/12159-codemetrics
it's waiting for approval, so it might not be available yet.
