### ISSUE TITLE
May lua language be supported in the future release?

### ISSUE THREAD

**Issue by liwangqian** [kisstkondoros/codemetrics#23]
There is a Lua AST parser written in JavaScript (namely [luaparse),](https://github.com/oxyc/luaparse).

**Comment by kisstkondoros** [comment]
I'm quite busy these days, but I might have a deeper look during the weekend.
Thanks for the idea!

**Comment by kisstkondoros** [comment]
Hi, 

Please check version 1.7.0, it's in the market with experimental support for Lua.
Any feedback is appreciated! 😄

**Comment by liwangqian** [comment]
@kisstkondoros 
nice work! it works but the complexcity algo is not what i want, as #28 describe.

**Comment by kisstkondoros** [comment]
@liwangqian What is the exact problem?
