### ISSUE TITLE
[Question] Provide details on how complexity is calculated

### ISSUE THREAD

**Issue by peterschussheim** [kisstkondoros/codemetrics#26]
Hi,

Recently started using this extension and it is neat however a brief explanation would be useful to myself and perhaps other users.

thanks,
Peter

**Comment by kisstkondoros** [comment]
Hi,

It is a pretty straight forward process (it is inspired by [Cyclomatic complexity](https://en.wikipedia.org/wiki/Cyclomatic_complexity)).
1. take the source code
2. transform it to [abstract syntax tree](https://en.wikipedia.org/wiki/Abstract_syntax_tree)
3. traverse the tree
4. use assigned complexity values / visibility settings from the configuration (see package.json for available settings under codemetrics.nodeconfiguration)
5. accumulate the subtotals for each node
6. display the result
7. be happy 😄 

I hope this answered your question. If not feel free to reopen the issue / file a new one and I'll further elaborate it.

**Comment by peterschussheim** [comment]
@kisstkondoros Thank you for the explanation, this helps! 🥇
