### ISSUE TITLE
Cannot read property 'document' of undefined

### ISSUE THREAD

**Issue by jrieken** [kisstkondoros/codemetrics#27]
I see this error a lot in production and when developing extensions it makes the debugger always break there...

```
Cannot read property 'document' of undefined: TypeError: Cannot read property 'document' of undefined
    at Timeout._onTimeout (/Users/jrieken/.vscode-insiders/extensions/kisstkondoros.vscode-codemetrics-1.7.0/out/editordecoration/EditorDecoration.js:40:59)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

<img width="836" alt="screen shot 2017-05-30 at 15 44 53" src="https://cloud.githubusercontent.com/assets/1794099/26586288/099dd6f0-454f-11e7-8c91-48139fd9aac3.png">

**Comment by kisstkondoros** [comment]
Hi, 

Thanks for reporting the bug!
Now the change callbacks are using vscode.window.activeTextEditor (and some null checks) to avoid this issue, however I can't think of a case where this could happen.

Hopefully this will fix the problem for you, but it is still interesting!
