### ISSUE TITLE
Show results in panel enable/disable?

### ISSUE THREAD

**Issue by maxx07** [kisstkondoros/codemetrics#29]
With version 1.7.0 the codemetrics results are shown on the panel triggered by Issue: https://github.com/kisstkondoros/codemetrics/issues/25. Is there a way to hide them there?
If not, would it be useful to make that configurable to be able to disable that?

**Comment by kisstkondoros** [comment]
Version 1.7.2 is coming with a flag which you can turn off to reach what You want:

Add
```
codemetrics.basics.DiagnosticsEnabled: false
```
to the workspace settings.
