### ISSUE TITLE
Class complexity in TS files

### ISSUE THREAD

**Issue by vharadkou** [kisstkondoros/codemetrics#30]
I want to see green complexity for classes which methods are green (4 methods with complexity 4 (green) = complexity 16 (green) for class. Not Red)

Actual: 
![image](https://user-images.githubusercontent.com/5987672/27868014-154a42f6-61a4-11e7-8622-b339c763af57.png)

Expected:
![image](https://user-images.githubusercontent.com/5987672/27868076-54f4325e-61a4-11e7-9d34-98b30bdc547c.png)

If any method has yellow complexity, the result for class should be yellow (the same for red)

**Comment by kisstkondoros** [comment]
Just published vscode-codemetrics@1.8.0, which takes the maximum complexity for class declarations (instead of sum).

I hope it's ok
