### ISSUE TITLE
Settings to exclude folder/files from codemetrics analysis

### ISSUE THREAD

**Issue by pmunin** [kisstkondoros/codemetrics#31]
How to exclude particular folder or file from code metric analysis.
E.g. I have a folder **/dist** or **/build**, which contains compiled js files, that I don't want to be analysed by CM, however I still see thousands of warnings in "PROBLEMS" tab for those files from codemetrics.

I don't want to exclude those folders from workspace either, I just want all code analysis tools to ignore those files.

**Comment by kisstkondoros** [comment]
vscode-codemetrics@1.9.0 was just published with this feature included, please open an issue if something feels wrong with it ^^

**Comment by pmunin** [comment]
Thanks for fast reaction, man! good job!
