### ISSUE TITLE
Object literal expression should default to 0

### ISSUE THREAD

**Issue by the-simian** [kisstkondoros/codemetrics#33]
```
function example() {
  return {
    a: {},
    b: {},
  };
}
```
this has a cyclomatic complexity of 1 (no branching whatsoever) and is given a complexity rating of 5, which is unusual.

**Comment by kisstkondoros** [comment]
Version 1.9.1 is available in the market, from that version the object literal does not affects the calculated complexity.

**Comment by the-simian** [comment]
Cant wait to update, thanks for the nice plugin, @kisstkondoros
