### ISSUE TITLE
Object literal 

### ISSUE THREAD

**Issue by hellsinglord22** [kisstkondoros/codemetrics#34]
when i pass argument as `object_literal` i get a high complexity level, is their anyway to reduce the complexity level for passing arguments as `object_literal` because i am doing this for clarification and readability in the first place .

**Comment by kisstkondoros** [comment]
Resolved in 1c2cb0655e4f8d8cef43e3d36aaecfe41c82ecb3

**Comment by kisstkondoros** [comment]
Version 1.9.1 is available in the market, from that version the object literal does affects the calculated complexity.
