### ISSUE TITLE
Enable metrics for arrow functions

### ISSUE THREAD

**Issue by sQVe** [kisstkondoros/codemetrics#35]
I've tried a couple of things but the only one that actually works is using the command "Toggle code lenses for arrow functions". I would like to set a setting in my user config so it is toggled on by default. `codemetrics.basics.MetricsForArrowFunctionsToggled` does not make any difference for me.

Is this already possible, if so how?

**Comment by kisstkondoros** [comment]
Thanks for the issue report, it was meant to be shown by default.
Please try it with v1.9.2 it is up in the market.

**Comment by sQVe** [comment]
@kisstkondoros It now works! Cheers for the quick fix!
