### ISSUE TITLE
some methods missing complexity estimate

### ISSUE THREAD

**Issue by ZuBB** [kisstkondoros/codemetrics#37]
See screen

<img width="1440" alt="screen shot 2017-10-01 at 15 46 28" src="https://user-images.githubusercontent.com/597016/31054663-8d93747e-a6c0-11e7-8734-125defcedf4d.png">

**Comment by kisstkondoros** [comment]
Thanks for the issue report, however this is an intended behavior:
https://github.com/kisstkondoros/codemetrics/blob/495cdc06a14a5ee4c05d2a96af7c3938061db2d7/package.json#L151

You can change this however by adding `codemetrics.basics.CodeLensHiddenUnder: 0` to the settings
