### ISSUE TITLE
help items to reduce complexity overlapping each other

### ISSUE THREAD

**Issue by ZuBB** [kisstkondoros/codemetrics#38]
See screen

<img width="993" alt="screen shot 2017-10-01 at 16 03 09" src="https://user-images.githubusercontent.com/597016/31054749-607aee0c-a6c2-11e7-8325-250dd029b40e.png">

**Comment by kisstkondoros** [comment]
Fair enough, fix is on the way. (I guess vscode changed the rendering of quick pick items)
