### ISSUE TITLE
Code Metrics breaks custom user settings

### ISSUE THREAD

**Issue by twhite96** [kisstkondoros/codemetrics#39]
I have to restart VS Code several times in order to keep certain user settings with this extension installed. I narrowed it down to this extension. Any way to find what is happening?

**Comment by kisstkondoros** [comment]
Thanks for the issue report!

I have no clue what might cause this, but I'm happy to help.
Which user settings are not persisted?

**Comment by kisstkondoros** [comment]
I close it because of missing information, if I can help feel free to file a new issue.
