### ISSUE TITLE
TypeScript code Complexity via Gulp Task

### ISSUE THREAD

**Issue by FlippieCoetser** [kisstkondoros/codemetrics#4]
Using a Gulp tasks to compute TypeScript Code Complexity outside Visual Studio can be super helpful.
Below is a sample of how code coverage are displayed.

![image](https://cloud.githubusercontent.com/assets/3672126/17179511/6fc1cb9c-5411-11e6-96dd-09a9c0998bec.png)

In addition, adding a configuration setting to produce a JSON or XML output will allow for the creation of a complete code metrics report. As of today I was unable to find any package for code complexity specifically for TypeScript. Please consider such a package.

**Comment by kisstkondoros** [comment]
Hi,

Thanks for the idea, I've actually started with the implementation, but I have limited time to work on it 😄 
I'll post here a link when it becomes usable.

**Comment by kisstkondoros** [comment]
So, here is the thing https://github.com/kisstkondoros/gulp-tsmetrics 🎆 

the core has been also separated, so that one can build e.g. a webpack loader or a grunt task around it.
It can be found here: https://github.com/kisstkondoros/tsmetrics-core.

**Comment by FlippieCoetser** [comment]
Thanks @kisstkondoros! everything installed and configured pretty easy. I'll post some possible improvements directly in the Gulp repository
