### ISSUE TITLE
Extract function into class refactoring does not work when code metrics is enabled

### ISSUE THREAD

**Issue by acepero13** [kisstkondoros/codemetrics#40]
When code metrics is enabled, and a portion of code is selected the quick fix bulb does not appear, neither pressing Cmd+. 
When the extension is disabled, the quick fix bulb appears again.

[Short video of the problem](https://www.dropbox.com/s/97or42dbmu32btk/Peek%202017-10-07%2009-49.gif?dl=0)

**Comment by kisstkondoros** [comment]
I'm going to investigate it further, but please try setting
```
"codemetrics.basics.DiagnosticsEnabled": false
```
for me it solved the problem. 
I think I'll change the default for this setting or provide an alternative command for refactoring.

**Comment by kisstkondoros** [comment]
Version vscode-codemetrics@1.9.6 has been published, it turns off the feature flag for the diagnostics by default, therefore solves the problem.
