### ISSUE TITLE
Support for .vue files

### ISSUE THREAD

**Issue by rmartins90** [kisstkondoros/codemetrics#41]
It's possible to add support for .vue files? Excellent plugin btw.

**Comment by kisstkondoros** [comment]
Version 1.10.0 is in the market with support for scripts inside script tags in vue and html files.
:fireworks:

**Comment by kisstkondoros** [comment]
P.S. https://github.com/vuejs/vetur is necessary for it to work
(actually just something which can identify .vue files as vue documents for vscode)

**Comment by ffxsam** [comment]
@kisstkondoros This still doesn't seem to work, and I have Vetur installed. Is there some other setup we need to do in order to make this work for `<script>` blocks in Vue files?

**Comment by kisstkondoros** [comment]
![image](https://user-images.githubusercontent.com/14231157/36564069-63400386-181c-11e8-9b54-92d6f2423e2e.png)

tested successfully with https://raw.githubusercontent.com/ffxsam/element/dev/examples/app.vue
extension version: 1.11.2 (latest)
vscode version: 1.21.0-insider
```
Version 1.21.0-insider
Commit eb5e41cfd5df83b126cccf7a5483b05878ef637f
Date 2018-02-22T06:16:07.194Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

@ffxsam Please file another issue with more details if possible.
