### ISSUE TITLE
[Feature request] Generate cyclomatic complexity report

### ISSUE THREAD

**Issue by GregOnNet** [kisstkondoros/codemetrics#42]
Hey there,

thanks for the this awesome plugin.
I use it every day. 👍 👍 👍 

Now I am working on a bigger project.
It has lots of huge methods and classes.
It would save me lots of time if I could simply generate a report telling me which file has classes and methods containing a complexity higher than `6 , 8 or 10`,

What do you think is it possible to add this feature?

Kind regards
Greg

**Comment by kisstkondoros** [comment]
There was already a similar request in #32 .
There I've linked a simple implementation for a webpack plugin. 
https://github.com/kisstkondoros/tsmetrics-webpack-plugin

Would that be sufficient?

**Comment by GregOnNet** [comment]
Hey, 

thanks for the quick response.
I defenetly will give it a shot.

I also see that my feature request would blow up the extension's code base.
I close this issue for now.

Kinds
Greg
