### ISSUE TITLE
Typescript spread operator stopping code from being evaluated by CodeMetrics

### ISSUE THREAD

**Issue by akrueger** [kisstkondoros/codemetrics#43]
Whenever I use the spread operator, nothing seems to evaluate afterwards. When I take it out, CodeMetrics seems to function normally.

With spread operator:
![screen shot 2017-11-16 at 11 06 05](https://user-images.githubusercontent.com/1644520/32905067-94ff7484-cabe-11e7-850a-91b244f32bbd.png)

Without spread operator:
![screen shot 2017-11-16 at 11 06 26](https://user-images.githubusercontent.com/1644520/32905074-9a27f86e-cabe-11e7-9a4a-c522d4d02dc3.png)

**Comment by kisstkondoros** [comment]
Fixed in v1.11.0
