### ISSUE TITLE
Feature request: scroll bar marker "decoration mode"

### ISSUE THREAD

**Issue by akrueger** [kisstkondoros/codemetrics#44]
Great work!

I have a suggestion based on another extension I use: [TODO Highlight](https://marketplace.visualstudio.com/items?itemName=wayou.vscode-todo-highlight), that has a handy marker in the right scroll column when a Todo highlight has been inserted.

It seems like a great feature to me to have that is similar to the "decoration mode" currently. It's unobtrusive, but I can easily check a file to see where I may have some fat functions, etc. I could imagine it being another flag alongside decoration mode:

```
  // A flag which indicates whether code metrics are shown as inline decoration
  "codemetrics.basics.DecorationModeEnabled": true,
```

Personally, I would probably turn off decoration mode and prefer the scroll bar decorator color as it would be out of the way of my code. Then I could scan on the right, and home-in on the more subtle code lens text.

![screen shot 2017-11-16 at 11 47 14](https://user-images.githubusercontent.com/1644520/32907007-48c34b76-cac4-11e7-8e9b-b6d2ac39eca7.png)

**Comment by kisstkondoros** [comment]
Shipped with v.1.11.0

You can configure it like this:
```json
{
    "codemetrics.basics.DecorationModeEnabled": false,
    "codemetrics.basics.OverviewRulerModeEnabled": true,
    "codemetrics.basics.CodeLensEnabled": false,
}
```
