### ISSUE TITLE
Duplicate message shown

### ISSUE THREAD

**Issue by cateyes99** [kisstkondoros/codemetrics#45]
## Environment data
VS Code version: `1.18.1`
**Code Metrics** Extension version: `1.11.0`

When hovering the mouse over the little coloured square, it sometimes shows duplicate messages (two or even many more), as the below one:
![image](https://user-images.githubusercontent.com/19678455/32985860-ed32b6e0-cd28-11e7-8742-a9a40eeac7ba.png)

After moved it to a new file and reloaded it, but this time it shows only one message:
![image](https://user-images.githubusercontent.com/19678455/32985940-35ccd99c-cd2b-11e7-96fe-1e50d8650c1b.png)

**Comment by kisstkondoros** [comment]
Thanks for reporting the issue, v1.11.1 was just released to fix this.
