### ISSUE TITLE
Possibilty to remove text

### ISSUE THREAD

**Issue by PhlppKnst** [kisstkondoros/codemetrics#48]
Hi,

is it possible to remove the text like "Complexity is 6 It's time to do something" above the function and just get a colored rectangle and the text is only shown as tooltip?

Best,
Phlpp

**Comment by kisstkondoros** [comment]
Yes, using the following in the user settings should actually do exactly that.
```json
{
    "codemetrics.basics.CodeLensEnabled": false
}
```
