### ISSUE TITLE
javascript function with one switch statement shows complexity 6

### ISSUE THREAD

**Issue by kedwin** [kisstkondoros/codemetrics#49]
javascript function with one switch statement shows complexity 6

ver: 1.11.2
vscode: 1.20.1

![screenshot from 2018-02-20 18-19-34](https://user-images.githubusercontent.com/10922690/36438588-aec53258-166a-11e8-9f98-e51587f4f11a.png)

```javascript
function test(something) {
    switch (something) {
        case 'test':

            break;

        default:
            break;
    }
}

```

**Comment by kisstkondoros** [comment]
And you can clearly see why when you click on the code lens ^^
However one can configure the weights to ignore certain expressions. See issue #14 for further details.
