### ISSUE TITLE
typing confuses things

### ISSUE THREAD

**Issue by jrieken** [kisstkondoros/codemetrics#5]
Since the last update the extension is often very confused and gives me seemingly random metrics in wrong places (like inside bodies, on classes etc)

![screen shot 2016-08-15 at 16 22 30](https://cloud.githubusercontent.com/assets/1794099/17667304/aa30f008-6304-11e6-8fa4-77384f91a48e.png)

**Comment by kisstkondoros** [comment]
Hi,

Thanks for reporting the issue, I knew I've wanted to do something during the refactor....
Sorry for the inconvenience.

Version 1.1.1 should now be available in the market 🎆 

Feel free to reopen the issue if the problem is still present!
