### ISSUE TITLE
Calculation always +1

### ISSUE THREAD

**Issue by andretf** [kisstkondoros/codemetrics#50]
I'm not sure if it's an issue or it's expected from your algorithm calculations.
Final sum is always added 1 point, seems it's putting function statement into account instead of just its body (`"codemetrics.luaconfiguration.FunctionDeclaration": 1`).

Please see image below, I think it's self explanatory.
![screenshot_20180220_223224](https://user-images.githubusercontent.com/5576877/36458560-2de43a16-168e-11e8-8227-0f26c81a1574.png)

text example:

    function a() { return 1 }
    function b(p) {
      return p ? 1 : 2
    }
    function c(p) { }

AFAIK, their cyclomatic complexity should be 1 for `a`, 2 for `b`, and 0 for `c`.

**Comment by kisstkondoros** [comment]
It is the expected behavior, but you can change the mentioned config property to 0, then it should behave as you described.
If not please create a new issue.

(The description in #14 might be useful)

**Comment by andretf** [comment]
Thank you for you quick response.
I'd like to mention that I was thinking your extension do a simple Cyclomatic Complexity.
It's nice to cover aspects where [CC fails in readability](https://www.cqse.eu/en/blog/mccabe-cyclomatic-complexity/).
Although it would be awesome to see in future releases McAbe CC (to help writing unit tests), Maintainability Index, etc.
