### ISSUE TITLE
Suggestion: place colored flag next to hit text to keep the indents intact visually

### ISSUE THREAD

**Issue by mackelito** [kisstkondoros/codemetrics#53]
yeah yeah.. I know.. but still.. it kind of bugs me ;)

**Comment by kisstkondoros** [comment]
It also bothers me, but I don't have an elegant solution in mind.
Perhaps an aggregated flag at the end of the line would be better? I don't know.

Would you be interested in a PR?

**Comment by mackelito** [comment]
Would love to but.. 2 kids and working 200%.. you know how it is :P

**Comment by kisstkondoros** [comment]
Same here ^^, but I'll keep this in mind.

**Comment by kisstkondoros** [comment]
vscode-codemetrics@1.13.0 was published with a relevant change in this topic.
Please let me know if it helped.

**Comment by mackelito** [comment]
Would you look at that!.. waaaay better! :D 
If you where here you would get a hug and a coffee!
