### ISSUE TITLE
Is there any support for custom colors

### ISSUE THREAD

**Issue by cris7ea** [kisstkondoros/codemetrics#54]
Great work!

Question: Is there any way to customize colors?

Why: I would like to distinguish between linting errors and complexity problems. Right now they have the same colors and it's hard to make the difference right away.

Example API:
```javascript
{
  "codemetrics.colors.high": "#FF2D00", // red
  "codemetrics.colors.med": "#FFB900", // orange
  "codemetrics.colors.low": "#F3FF00" // yellow
}
```

Where to add custom colors?:
![Add custom colors](https://user-images.githubusercontent.com/1644520/32907007-48c34b76-cac4-11e7-8e9b-b6d2ac39eca7.png)

**Comment by kisstkondoros** [comment]
Version 1.14.0 was just published which contains the requested feature.
Example configuration:
```json
    "codemetrics.basics.ComplexityColorLow": "#333",
    "codemetrics.basics.ComplexityColorNormal": "#666",
    "codemetrics.basics.ComplexityColorHigh": "#999",
    "codemetrics.basics.ComplexityColorExtreme": "#CCC",
```

**Comment by cris7ea** [comment]
Thank you!
