### ISSUE TITLE
DOC: How complexity is calculated

### ISSUE THREAD

**Issue by mdugue** [kisstkondoros/codemetrics#55]
I think this is a very interesting approach and might be a well needed extension. Though I have the impression, that onboarding is a bit difficult, due to not knowing how complexity is calculated (unless reading through the settings and the "in-IDE" explanations). 

@kisstkondoros What do you think about having an introductory part in the readme explaining the applied default values? Having them clearly communicated in a central place might also enable to a lively discussion about strong / good default values and best practices. In case you are using some "standard" that I'm missing here, maybe you could point to it.

Thanks & Cheers!

**Comment by kisstkondoros** [comment]
Thanks for filing the issue, version 1.16.0 is in the market already with an updated description.
Since this was not the first time someone asked it really made sense...
If you have suggestions on how to improve it don't hesitate to file another issue or create a pull request ^^.
