### ISSUE TITLE
Color decoration moves to next level before description does.

### ISSUE THREAD

**Issue by mvanthoor** [kisstkondoros/codemetrics#58]
Thanks for this extension. Very helpful, but I think I've found a bug.

Reproduction:

- Set "codemetrics.basics.ComplexityLevelNormal": 4 
- Create a function. The complexity is 1. The description and color both show the ones set for the Low level.
- Add some "if (true) {}" to the function to increase complexity.
- As soon as the complexity reaches 4, the description shows the one set for low complexity, while the color shows the one set for normal complexity.
- The same thing (color moving to the next level one step before the description) happens in the entire range.

![c1](https://user-images.githubusercontent.com/40828618/42276382-ec04922a-7f93-11e8-9d92-811839af697c.png)
![c3](https://user-images.githubusercontent.com/40828618/42276383-ec237da2-7f93-11e8-8398-578a3ade1d94.png)
![c4](https://user-images.githubusercontent.com/40828618/42276384-ec3f9352-7f93-11e8-8a58-b8462496b2e8.png)

Thanks for looking into it :)

**Comment by kisstkondoros** [comment]
Thanks for reporting the bug, it turned out to be a stupidity of mine ^^

Version 1.17.0 is available in the market, which contains (amongs others) the fix for this as well.
