### ISSUE TITLE
"It"s time to do something..." appears

### ISSUE THREAD

**Issue by sean-mcmanus** [kisstkondoros/codemetrics#6]
"It"s time to do something...", should be "It's".

Using this setting fixes it: "codemetrics.basics.ComplexityLevelNormalDescription": "It's time to do something...",

![itstime](https://cloud.githubusercontent.com/assets/19859882/18886400/8c87aeea-84a4-11e6-813f-aa4ed6e41d4c.png)

**Comment by kisstkondoros** [comment]
Thanks for reporting the issue!
Fixed in v 1.1.3.
