### ISSUE TITLE
React JSX

### ISSUE THREAD

**Issue by johnstew** [kisstkondoros/codemetrics#60]
Hi there, quick question. I noticed the complexity for each React component is returning a 1. Is that correct?

**Comment by kisstkondoros** [comment]
Hi, yes it is correct.
However if the behavior does not matches the expectations one could configure it in the user/workspace settings (settings.json in .vscode folder)
```json
    "codemetrics.nodeconfiguration.JsxElement": 0,
    "codemetrics.nodeconfiguration.JsxSelfClosingElement": 0,
```

**Comment by johnstew** [comment]
thanks!
