### ISSUE TITLE
Rounding of complexity number

### ISSUE THREAD

**Issue by kimmoahola** [kisstkondoros/codemetrics#65]
Hi,

Thank you for the VS code extension!

I would suggest some kind of a rounding of the complexity number. I have the default settings, except:

```
  "codemetrics.nodeconfiguration.ReturnStatement": 0.1,
  "codemetrics.nodeconfiguration.CaseClause": 0.1,
  "codemetrics.nodeconfiguration.DefaultClause": 0.1,
```

With that setting I get way too much precision on the number:

<img width="393" alt="image" src="https://user-images.githubusercontent.com/28525546/58068527-5d2e3480-7b9a-11e9-99ce-8a157b87c075.png">

Only 2-3 meaningful number would be enough. In this case the number would be "10.4", or even just "10".

**Comment by kisstkondoros** [comment]
I'll check it later, I've never thought anyone would use decimals here. :smile:

**Comment by kisstkondoros** [comment]
Version 1.18.1 should soon be available in the market, it will contain the fix for this.

**Comment by kimmoahola** [comment]
Seems to work. Thanks!
