### ISSUE TITLE
Arrow disable not work correct

### ISSUE THREAD

**Issue by Mordef** [kisstkondoros/codemetrics#66]
Like #62 in TS-File
![grafik](https://user-images.githubusercontent.com/22061464/58180447-69091c00-7caa-11e9-820f-bca1bc0ffc8b.png)

Settings:
"codemetrics.nodeconfiguration.ArrowFunction": 0,

Also for Funtion needed or how can i fix something like this:
`
foo.addEventListener('click', function (event) { _this.dosomething(event); });
`

**Comment by kisstkondoros** [comment]
Thanks for reaching out!

1:
To hide the code lens over arrow functions : ```MetricsForArrowFunctionsToggled: false```
or use the `Toggle code lenses for arrow functions` command

2:
```foo.addEventListener('click', function (event) { _this.dosomething(event); });```
is equivalent with
```
var handler = function (event) { _this.dosomething(event); }
foo.addEventListener('click', handler);
```
which is the same (functionality wise, in this example) as
```
var handler = _this.dosomething.bind(_this);
foo.addEventListener('click', handler);
```

**Comment by Mordef** [comment]
Thanks for fast answer
