### ISSUE TITLE
Not working with RemoteWSL extension in VSCode

### ISSUE THREAD

**Issue by bogdan-calapod** [kisstkondoros/codemetrics#68]
Hello,

First of all, thanks  a lot for this extension, I find it very useful! :) 

It seems that the extensions doesn't get along very well with VSCode's WSL Remote insiders (or maybe I haven't configured something properly?)

In a WSL Workspace, the extension doesn't output anything to the debug window, but the code metrics don't show up. I have set the threshold at 0, and have toggled code metrics with the option in the `Ctrl + Shift + P` menu.

Any idea how I can help debug this further ?

**Comment by kisstkondoros** [comment]
Thanks for reporting it, I'll have a look.
I suspect it has something to do with the url scheme.

**Comment by kisstkondoros** [comment]
I've just tested it with Remote-WSL with a docker based setup: for me it works.
Could you please provide more information about your environment?

**Comment by bogdan-calapod** [comment]
Sorry for the late reply, I've been away for a couple of days.

I've noticed that it's pretty sporadic - sometimes it shows, sometimes not. Might it be from the cocktail of extensions I have ?

I suspect extensions that also use codelens to display info in the editor might be clashing with one another ? Culprits that I have installed might be:

* GitLens
* VSCode-Jest


I have noticed that if I disable VSCode-Jest for the workspace I'm working in CodeMetrics works more reliably. There's also an [issue](https://github.com/jest-community/vscode-jest/issues/455) regarding high CPU usage with the extension - maybe something doesn't get executed in time because Jest takes up all the CPU space ?

I'll make more tests over the following days with various configs and try to track this down.

**Comment by kisstkondoros** [comment]
I don't think it has anything to do with that, at least it shouldn't :smile:

If you toggle codelens with the command menu they will not show up for sure (by default they are visible and you can turn them off that way).

I'm waiting for some more info then.
Please try to provide a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) if possible. The list of installed extensions and the settings file of vscode would also be useful.

Thanks in advance!

**Comment by kisstkondoros** [comment]
I'll close this ticket for now, but feel free to reopen / add further details / create a new issue with more information.

**Comment by bogdan-calapod** [comment]
Cool - I've tested with the latest June release and can't seem to reproduce it. If it pops up again, I'll let you know.
