### ISSUE TITLE
Docs (README): Customization options reference sub-optimal

### ISSUE THREAD

**Issue by Izhaki** [kisstkondoros/codemetrics#69]
The README currently states:

> for a complete list check AppConfiguration.ts

However, that file is hardly informative as to what the options are.

I had to look at `package.json` for what I was looking for (`OverviewRulerModeEnabled `).

I think the RADME should change to:

> for a complete list check the configuration section in package.json

**Comment by kisstkondoros** [comment]
Thanks for pointing it out! It was slightly adjusted in v1.20.0.
