### ISSUE TITLE
Errors do not appear to have any guidance on why they have been picked up

### ISSUE THREAD

**Issue by mildfuzz** [kisstkondoros/codemetrics#7]
Should these errors not have more details? Feels I am missing something

![image](https://cloud.githubusercontent.com/assets/196705/20186033/50a33090-a766-11e6-814e-a48296a788eb.png)

**Comment by kisstkondoros** [comment]
Please check the updated version (1.1.4). 
I've adjusted a bit the quick pick representation.

![image](https://cloud.githubusercontent.com/assets/14231157/20240885/9150e834-a924-11e6-9954-a3e16565b4a1.png)

I'm curious if that makes it more usable for you, if not I'm open for suggestions 😄
