### ISSUE TITLE
Counts seem off by 1... 

### ISSUE THREAD

**Issue by yyyc514** [kisstkondoros/codemetrics#70]
The comment say 4 complexity but then Code Lens will only show 3...  Every single time it always seems to be consistently off by 1.

Thoughts?

<img width="637" alt="Screen Shot 2019-08-30 at 2 42 13 AM" src="https://user-images.githubusercontent.com/6473/63998725-cb569180-cacf-11e9-898c-09cb6bbb67e7.png">

**Comment by kisstkondoros** [comment]
Yes, the method declaration itself is also +1 by default, I'll think about adding it to the list also.

**Comment by yyyc514** [comment]
OH, that's not clear at all. ;-)  At least now I know it's not broken.

**Comment by kisstkondoros** [comment]
Version 1.21.0 was just released which should fix this.

**Comment by yyyc514** [comment]
Awesome. Thanks.
