### ISSUE TITLE
Listed entries do not display completely

### ISSUE THREAD

**Issue by Acgsior** [kisstkondoros/codemetrics#72]
Click the code lens link and popup the window with cause entries, however, their causes are not display completely.
![snapshot 2019-09-04 15 45 09](https://user-images.githubusercontent.com/2238860/64235918-eee46680-cf2b-11e9-9d1c-3415aa51d108.png)

**Comment by kisstkondoros** [comment]
Thanks for the issue report, version 1.23.0 was just released with a fix for this (and some cosmetics around it).
