### ISSUE TITLE
Feature request: Setting for folders/function names to ignore

### ISSUE THREAD

**Issue by GregorBiswanger** [kisstkondoros/codemetrics#73]
Hi,
first of all.. I love your extension! Thank you for your work...

I have only one problem with spec files. This have a lot of test functions and the result of complexity on the describe function is not required.. we need a workspace settings, for ignore folder/function names as example..

Thanks..

**Comment by kisstkondoros** [comment]
You could use ```codemetrics.basics.Exclude``` for exactly this.
Let me know if it helped. Until that I'll close the issue.

**Comment by IgnusG** [comment]
Is it possible to only exclude the describe function but keep the statistic for tests?

For Example remove this red annotation?
![image](https://user-images.githubusercontent.com/6438760/80530055-bd2b7e80-8998-11ea-917d-540e242c9c68.png)
