### ISSUE TITLE
external config file to customize code metrics

### ISSUE THREAD

**Issue by pixelbits-mk** [kisstkondoros/codemetrics#76]
how do I specify an external configuration file to customize code metrics? I'm looking for something similar to tslint.json for linting, where the config file can be checked into source control, but used by Visual Studio Code in the editor UI.

**Comment by kisstkondoros** [comment]
Thanks for opening an issue!

I'll close this as I have no impact on this.

microsoft/vscode#15909 is about exactly this.
Maybe drop some words there too about your use-case.
