### ISSUE TITLE
Auto focusing when moving from Listed entries?

### ISSUE THREAD

**Issue by CatsMiaow** [kisstkondoros/codemetrics#77]
![image](https://user-images.githubusercontent.com/1300172/72864937-3885f000-3d19-11ea-8071-e1d29f6ea2c2.png)
I want to move to a place when moving up and down in the above list.

https://code.visualstudio.com/docs/editor/editingevolved#_go-to-symbol
Like `Go to Symbol` in VS Code.

![find_by_symbol](https://user-images.githubusercontent.com/1300172/72865192-412af600-3d1a-11ea-8eb5-1e4ed7f0d0e5.gif)

**Comment by kisstkondoros** [comment]
Thanks for the issue report!

I've adjusted the quick pick behavior in 1.24.0.
