### ISSUE TITLE
project complexity 

### ISSUE THREAD

**Issue by jikhww** [kisstkondoros/codemetrics#79]
i'm a team leader,and i want count all function's complexity in the project。 it‘s better generate a report (eg html,markdown) and sorted by complexity 。

我是一个团队leader,想统计项目内部所有函数的复杂度,最好是按照复杂度排序并生成一个报表

**Comment by kisstkondoros** [comment]
There is a project which is built on top of the same code complexity calculation logic:
https://github.com/kisstkondoros/codemetrics-cli.

I have no plans of implementing something like that as I'm against using such complexity measures as any sort of KPI.
