### ISSUE TITLE
Complexity info is not on the correct place

### ISSUE THREAD

**Issue by ivaylopivanov** [kisstkondoros/codemetrics#8]
With "window.zoomLevel": 2 and with vs code 1.7, the info about the complexity is shown in the explorer tab. I'm using the latest version of the extension.
![screen shot 2016-11-11 at 12 15 18](https://cloud.githubusercontent.com/assets/8849904/20213495/38a2d2ea-a809-11e6-9967-f4718285543d.png)

**Comment by kisstkondoros** [comment]
Thanks for noticing it, but it is a vscode issue, please report it there.
(I had already a look where it is messed up in the core vs code and it seems position: fixed is applied instead of position: absolute to the codelens widget)

**Comment by kisstkondoros** [comment]
Forwarded to vscode team.

**Comment by kisstkondoros** [comment]
Please update to the latest insider build, it appears to be fixed there!
