### ISSUE TITLE
Option to deactivate error like highlighting

### ISSUE THREAD

**Issue by BridgeAR** [kisstkondoros/codemetrics#80]
I like the plugin quite a lot but it's difficult to use for me, since the indicator is strongly highlighted in the mini map.

This reduces the usability for me, since I mostly want to see errors such as linting errors. It would be great if this could be configured.

**Comment by kisstkondoros** [comment]
Could it be that `codemetrics.basics.OverviewRulerModeEnabled` would solve this issue for you?

Feel free to reopen if this did not worked.
