### ISSUE TITLE
Hide "green" complexities

### ISSUE THREAD

**Issue by BridgeAR** [kisstkondoros/codemetrics#81]
Right now the plugin is pretty verbose by always showing the complexity. If something is already good, there is not really a reason to outline it.

I suggest to either add an option to hide specific levels or to make it an default to hide good complexities.

**Comment by kisstkondoros** [comment]
Thanks for reaching out!

I think `codemetrics.basics.CodeLensHiddenUnder` is what you are looking for (default value is '3'). This is independent of the complexity levels intentionally.

If you think the behavior is not satisfying, please open a new more specific issue, I'm open for suggestions.

**Comment by BridgeAR** [comment]
Thank you very much, I did indeed somehow miss these configurations.
