### ISSUE TITLE
Output as a list?

### ISSUE THREAD

**Issue by jpragit** [kisstkondoros/codemetrics#85]
Sorry if this is a dumb question, but I see that the extension displays complexity inline with the code.  Is there a way to get a list?  Maybe one with totals or averages?  Sort of the way Code Metrics works in Visual Studio?

**Comment by thangaraja** [comment]
+1

**Comment by Gowtham029** [comment]
+1

**Comment by kisstkondoros** [comment]
Thank for reaching out!

This was already requested in
https://github.com/kisstkondoros/codemetrics/issues/32
https://github.com/kisstkondoros/codemetrics/issues/42
https://github.com/kisstkondoros/codemetrics/issues/56

TLDR;
I've published two small tools for generating something like this and it is out of scope of this particular extension.
