### ISSUE TITLE
[Question] Can I somehow hide color marks on minimap?

### ISSUE THREAD

**Issue by Demetri0** [kisstkondoros/codemetrics#89]
Is there a possibility to disable color highlights on the minimap? I found an option `codemetrics.basics.CodeLensHiddenUnder` but it also disables descriptions above functions.

I would like to disable only color highlights on minimap because it adds messing with real errors in code.

![Screenshot from 2021-03-06 16-33-45](https://user-images.githubusercontent.com/6806547/110203684-c24f3900-7e99-11eb-9e01-2570a79e4895.png)

**Comment by kisstkondoros** [comment]
Try codemetrics.basics.OverviewRulerModeEnabled instead
