### ISSUE TITLE
Support Visual Studio Code 1.9

### ISSUE THREAD

**Issue by bcbcarl** [kisstkondoros/codemetrics#9]
The Visual Studio Code 1.9 throws an error after executed `Toggle code metrics`:

`command 'codemetrics.toggleCodeMetricsDisplayed' not found`

![screen shot 2017-02-04 at 2 47 38 pm](https://cloud.githubusercontent.com/assets/135734/22616496/09388e6e-eae9-11e6-88f4-bbf83915f6c8.png)

**Comment by kisstkondoros** [comment]
Thanks for the issue report.
I've just published v1.1.6 to the market, updating to it should solve the problem.
