### ISSUE TITLE
Feature Request: Support more languages (specifically C++)

### ISSUE THREAD

**Issue by benaxelrod** [kisstkondoros/codemetrics#99]
This looks like a super helpful extension.  I wish it supported my primary language: C++.

I see that this other complexity extension (https://marketplace.visualstudio.com/items?itemName=selcuk-usta.code-complexity-report-generator) supports many languages.  Maybe see what they use behind the scenes?

**Comment by kisstkondoros** [comment]
It seems to be using a rest API which in turn uses https://github.com/terryyin/lizard (python) to parse the AST.

AFAIK there is no good alternative in node for this.
